---
name: seer
version: 0.1.0
github: "saschagrunert/seer"
license: MIT
author: "Sascha Grunert"
maintainer: "mail@saschagrunert.de"
copyright: "Copyright (c) 2018 Sascha Grunert"
tested-with: GHC == 7.10.2, GHC == 7.10.3,
  GHC == 8.0.2, GHC == 8.2.2

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: A collaborative product vision, roadmap and resource planning tool.
category: Tools
description: Please see the README on Github at
  <https://github.com/saschagrunert/seer#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - bytestring
    - process

executables:
  seer-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - seer

tests:
  seer-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - bytestring
      - hspec
      - seer
      - tasty
      - tasty-hspec
      - tasty-smallcheck
      - test-fixture
